- name: Stow spicetify config
  copy:
    src: spicetify/config.ini
    dst: ~/.config/spicetify/config.ini

- name: Stow Dribbblish user.css
  copy:
    src: spicetify/user.css
    dst: ~/.config/spicetify/Themes/Dribbblish/user.css

- name: Stow Dribbblish color.ini
  template:
    src: spicetify/color.ini
    dst: ~/.config/spicetify/Themes/Dribbblish/color.ini

- name: Stow dribbblish.js
  copy:
    src: spicetify/dribbblish.js
    dst: ~/.config/spicetify/Extensions/dribbblish.js

- name: Reload spicetify
  shell: "spicetify -q update; [ ! -z $(pidof -s spotify) ] && spicetify -q restart || true"
